name: ci

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:
    paths-ignore:
      - '**.md'

jobs:
  plugin_test:
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Running asdf's plugin-test
        uses: asdf-vm/actions/plugin-test@v1.0.1
        with:
          command: jq --version
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
